---
# vars file for deploy_webserver
#nginx_yum_repo_enabled: true
server_name: "app.local" # тут ваш домен
php_default_version_debian: "7.4"
php_version: "7.4"

nginx_vhosts:
  - listen: 80
    server_name: "{{ server_name }}"
    root: "/var/www/html"
    index: "index.php index.html index.htm"
    error_page: "500 502 503 504 /50x.html"
    access_log: "/var/log/nginx/{{ vm_name }}.access.log main"
    error_log: ""
    state: "present"
    template: "{{ nginx_vhost_template }}"
    filename: "{{ vm_name }}.conf"
    extra_parameters: |
      location ~ \.php$ {
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass unix:/run/php/php-fpm.sock;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          include fastcgi_params;
      }


php_webserver_daemon: "nginx"
php_packages_state: "latest"
php_enable_php_fpm: true
php_executable: "php"
php_memory_limit: "128M"
php_max_execution_time: "90"
php_upload_max_filesize: "64M"
php_date_timezone: "Europe/Moscow"


php_packages:
  - php{{php_default_version_debian}}
  - php{{php_default_version_debian}}-fpm
  - php{{php_default_version_debian}}-cli
  - php{{php_default_version_debian}}-common
  - php{{php_default_version_debian}}-gd
  - php{{php_default_version_debian}}-mbstring
  - php{{php_default_version_debian}}-pdo
  - php{{php_default_version_debian}}-xml
  - php{{php_default_version_debian}}-curl
  - php{{php_default_version_debian}}-gd
  - php{{php_default_version_debian}}-mbstring
  - php{{php_default_version_debian}}-xml
  - php{{php_default_version_debian}}-xmlrpc
  - php{{php_default_version_debian}}-soap
  - php{{php_default_version_debian}}-intl
  - php{{php_default_version_debian}}-zip
  - php{{php_default_version_debian}}-mysql