---
# tasks file for deploy_haproxy

- name: Create self-signed certificate, if configured.
  command: >
    openssl req -x509 -nodes -subj '/CN={{ vm_name }}' -days 365
    -newkey rsa:4096 -sha256 -keyout "/etc/ssl/private/{{ vm_name }}.key" -out "/etc/ssl/certs/{{ vm_name }}.crt"
    creates="/etc/ssl/certs/{{ vm_name }}.crt"