---
- hosts: localhost
  connection: local

  vars_files:
  - vars/password.yml
  - vars/ovirtvm_vars.yml

  roles:
    - role: deploy_vm_ovirt
      vars:
        vm_name: "mysqldb.local"
      tags: db
    - role: deploy_vm_ovirt
      vars:
        vm_name: "haproxy.local"
      tags: proxy
    - role: deploy_vm_ovirt 
      vars:
        vm_name: "app01.local"
      tags: app
    - role: deploy_vm_ovirt
      vars: 
        vm_name: "app02.local" 
      tags: app