---
- hosts: app01
  become: true

  vars_files:
    - vars/main.yml
  roles:
    - role: deploy_webserver
      vars: 
        vm_name: "app01.local"  
    - role: geerlingguy.nginx 
      vars:
        vm_name: "app01.local"
    - geerlingguy.php

- hosts: app02
  become: true

  vars_files:
    - vars/main.yml
  roles:
    - role: deploy_webserver
      vars: 
        vm_name: "app02.local"
    - role: geerlingguy.nginx 
      vars: 
        vm_name: "app02.local" 
    - geerlingguy.php