all:
  children:
    webservers:
      hosts:
        geekbrains:
          ansible_host: geekbrains.local
        app01:
          ansible_host: app01.local
        app02:
          ansible_host: app02.local
        haproxy:
          ansible_host: haproxy.local
      vars:
        ansible_user: sa
        ansible_python_interpreter: /usr/bin/python3
    databases:
      hosts:
        mysqldb:
          ansible_host: geekbrains.local
      vars:
        ansible_user: sa
        ansible_python_interpreter: /usr/bin/python3
