all:
  children:
    webservers:
      hosts:
        geekbrains:
          ansible_host: geekbrains.local
      vars:
        ansible_user: sa
        ansible_python_interpreter: /usr/bin/python3
        php_webserver_daemon: "nginx"
